storage_service:
  - name: "CA-TRIUMF-DYNAFED"
    id: "atlas-fed-fe1.triumf.ca"
    quality: "testing"
    storage_endpoints:
      - id: "atlas-fed-fe1.trium.ca:443/dynafed"
        quality: "testing"
        interface: "https"
        implementation: "dynafed"
        implementationVersion: "1.5.0"
    storage_shares:
      - id: "atlas-fed-fe1.triumf.ca/dynafed/atlas/atlasdatadisk"
        name: "ATLASDATADISK"
        path:
          - "dynafed/atlas/atlasdatadisk"
        capacity:
          id: "atlas-fed-fe1.triumf.ca/dynafed/atlas/atlasdatadisk/s3"
        dynafed_endpoints:
          - id: "TRIUMF-S3-ATLASDATADISK01"
        access_policy:
          id: "atlas-fed-fe1.trium.ca:443/dynafed/ap/basic"
          rule:
            - "atlas"
            - "dteam"
            - "ops"
          scheme: "basic"
      - id: "atlas-fed-fe1.triumf.ca/dynafed/atlas/atlasscratchdisk"
        name: "ATLASSCRATCHDISK"
        path:
          - "dynafed/atlas/atlasscratchdisk"
        capacity:
          id: "atlas-fed-fe1.triumf.ca/dynafed/atlas/atlasscratchdisk/s3"
        dynafed_endpoints:
          - id: "TRIUMF-S3-ATLASSCRATCHDISK01"
        access_policy:
          id: "atlas-fed-fe1.trium.ca:443/dynafed/ap/basic"
          rule:
            - "atlas"
            - "dteam"
            - "ops"
          scheme: "basic"
